version: "2"

services:
  tests:
    image: quay.io/keboola/docker-custom-python:latest
    tty: true
    stdin_open: true
    working_dir: /src/
    command: python -m unittest discover
    volumes:
      - ./:/src/
    environment:
      - KBC_DATADIR=/src/test/data/
